/* 🤖 this file was generated by svg-to-ts*/
export const shop028Yugoslavia: {
  name: '028-yugoslavia';
  data: string;
} = {
  name: '028-yugoslavia',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M485.668 322.13l-70.066-161.066L485.668 0H26.331v512h321.727v-30H144.392V322.13zM56.332 30h383.571l-27.289 62.732H56.332zm0 92.732h343.231l-16.676 38.333 16.676 38.334H56.332zM114.392 482h-58.06V322.13h58.061V482zm-58.06-189.87v-62.732h356.282l27.289 62.732z"/></svg>`
};
