/* 🤖 this file was generated by svg-to-ts*/
export const shop026ShoppingBag: {
  name: '026-shopping-bag';
  data: string;
} = {
  name: '026-shopping-bag',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M430.561 123.666h-81.366V93.194C349.195 41.807 307.388 0 256 0s-93.195 41.807-93.195 93.194v30.472H81.44L69.88 512h372.24zM411.213 482H100.787l2.153-72.333h306.12zM319.195 93.194v30.472H192.806V93.194C192.806 58.349 221.155 30 256 30s63.195 28.349 63.195 63.194zm82.245 60.473l6.727 226H103.833l6.728-226z"/><path d="M166.333 313.667h179.333v-94H166.333zm30-64h119.333v34H196.333z"/></svg>`
};
