/* 🤖 this file was generated by svg-to-ts*/
export const shop018TermsAndConditions: {
  name: '018-terms-and-conditions';
  data: string;
} = {
  name: '018-terms-and-conditions',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M54.334 0v512H352.88l104.787-104.787V0zm30 30h343.333v349.667H325.333V482h-241V30zm328.452 379.667l-57.453 57.453v-57.453z"/><path d="M192 91.667h128v30H192zM133.333 166.333h245.333v30H133.333zM133.333 230.333h245.333v30H133.333zM133.333 294.333h245.333v30H133.333zM133.333 379.667h31.499v30h-31.499zM194.833 379.667h61.168v30h-61.168z"/></svg>`
};
