/* 🤖 this file was generated by svg-to-ts*/
export const shop011DeliveryBox: {
  name: '011-delivery-box';
  data: string;
} = {
  name: '011-delivery-box',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M108.666 54.333v66.333H53.333v30h55.333v31.667H0v30h108.666v87.333H53.333v30h55.333v31.667H0v30h108.666v66.333H512V54.333zM482 427.667H138.667V84.333h114v165.333H368V84.333h114zM338 84.333v135.333h-55.333V84.333z"/><path d="M177 388.333h104.667v-90H177zm30-60h44.666v30H207zM337 298.333h104.666v30H337zM404.333 358.333h37.333v30h-37.333zM337 358.333h37.333v30H337z"/></svg>`
};
