stages: 
  - install
  - build
  - test


default: 
  image: node:lts-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths: 
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

install_dependencies: 
  stage: install
  script: npm install

build_app: 
  stage: build
  script: nx build shoe-app --prod

test_app:
  stage: test
  script: nx test shoe-app