module.exports = {
  projects: [
    '<rootDir>/apps/shoe-app',
    '<rootDir>/libs/shoes/page/shoe-list',
    '<rootDir>/libs/shoes/ui/shoe-filter',
    '<rootDir>/libs/shoes/ui/shoe',
    '<rootDir>/libs/shoes/shared/services/shoes-service',
    '<rootDir>/libs/shoes/shared/types',
    '<rootDir>/libs/shoes/shared/assets',
    '<rootDir>/libs/shoes/ui/header',
    '<rootDir>/libs/shoes/page/home',
    '<rootDir>/libs/shoes/shared/services/user-service',
    '<rootDir>/libs/shoes/shared/services/cart-service',
    '<rootDir>/libs/shoes/shared/services/wishlist-service',
    '<rootDir>/libs/shoes/page/cart',
    '<rootDir>/libs/shoes/ui/cart-items',
    '<rootDir>/libs/shoes/ui/cart-item',
    '<rootDir>/libs/shoes/ui/cart-detail',
  ],
};
